server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:QE5jUmZVallYbjJyNXU4eC9BP0QoRytLYlBQZHNnVmtZcA==}
      # 86400000 ms = 24 horas
      expiration: 86400000
      refresh-token:
        # 604800000 ms = 7 d√≠as
        expiration: 604800000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pruebaPW
    username: postgres
    password: system
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true